### ISSUE TITLE
several jobs are logging errors `TypeError: fetch failed`

### ISSUE THREAD

**Issue by gobengo** [web3-storage/backup-progress#1]
```
4/3/2023, 11:41:04 AM | 2023-04-03T18:41:04.273Z backup:nft-0.json TypeError: fetch failed | backup
-- | -- | --
4/3/2023, 11:41:04 AM | at Object.fetch (node:internal/deps/undici/undici:11413:11) | backup
4/3/2023, 11:41:04 AM | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) | backup
4/3/2023, 11:41:04 AM | at async file:///usr/src/app/ipfs-client.js:57:19 | backup
4/3/2023, 11:41:04 AM | at async withChunkTimeout (file:///usr/src/app/ipfs-client.js:101:22) | backup
4/3/2023, 11:41:04 AM | at async IpfsClient.dagExport (file:///usr/src/app/ipfs-client.js:54:5) | backup
4/3/2023, 11:41:04 AM | at async exportCar (file:///usr/src/app/index.js:175:22) | backup
4/3/2023, 11:41:04 AM | at async file:///usr/src/app/index.js:74:30 | backup
4/3/2023, 11:41:04 AM | at async next (node:internal/streams/from:85:11)
```

* There are other jobs doing the same, e.g. `nft-27.json`
* Potentially all unfinished jobs are failing due to this, because right now there are no good logs coming from the `tail.js` script documented by this repo's readme

**Comment by gobengo** [comment]
It's from here. https://github.com/web3-storage/backup/blob/main/ipfs-client.js#L57
It could be because it hit the timeout, but the `TypeError: fetch failed` makes me think it failed before that. Maybe whatever is suppsoed to be running at `HOST` failed, and restarting the job will have it set itself up again?
That's my theory, and if it's right, then restarting nft-0.json might work. I'll try that.

**Comment by gobengo** [comment]
I restarted nft-0.json task. It looks like it's checking the batch again from the beginning, and logging a lot of "is already in S3" messages, but no new errors. I'll check back later and see if it breaks at the same place as before, or perhaps it will get further.

**Comment by gobengo** [comment]
After restarting, the nft-0 task is back up and logging things like this:
```
{
    "sourceDataFile": "nft-0.json",
    "cid": "QmZmjwcJFXQF5U28yobwb8xkJfMBg85wrrTUv3gmpUKQa3",
    "status": "ok",
    "size": 66674
}
```
(2023-04-03T12:10:13.292-07:00)


And I see lines like this come out of the `tail.js` script output
```
2023-04-03T19:23:41 {"sourceDataFile":"nft-0.json","cid":"QmXL1RiENwQe3h2q251mxjjz9jnBLouCKeaafPppPwADy3","status":"ok","size":1682}
2023-04-03T19:23:41 {"sourceDataFile":"nft-0.json","cid":"QmfQ1cqkYsWJdmhg2Uf8UxALkKQV98KBaNeD5qPFGwDtR3","status":"ok","size":237059}
```

This leads me to think that restarting was a reasonable thing to do, and now it's getting further.
(ostensibly the ipfs daemon had died for one reason or another before)
